name: Multi-purpose issue template example
description: Description goes here
assignees:
  - test
body:
  - type: dropdown
    id: issue-type
    attributes:
      label: What type of issue are you creating?
      description: Is this an Epic / User Story / Task / ?
      multiple: false
      options:
        - Epic
        - User story
        - Task
        - Bug
    validations:
      required: true
  - type: textarea
    id: requirements
    attributes:
      label: Requirements
      description: "What are the high-level goals that should be accomplished/addressed via closing this issue?"
      value: Use '# to link to the issue/epic/PR/etc that is key driver of this issue.
  - type: textarea
    id: requirements
    attributes:
      label: Requirements
      description: "What are the high-level goals that should be accomplished/addressed via closing this issue?"
      value: |
        1. Example 1
    validations:
      required: true
  - type: checkboxes
    id: did-you
    attributes:
      label: Did you remember to...?
      description: Did you remember to do these things?
      options:
        - label: Coordinate with PM...
        - label: Coordinate with relevant non-dev stakeholders?
        - label: Etc
  - type: textarea
    id: user-stories
    attributes:
      label: User stories
      description: Who are the users impacted/driving this issue and what are their needs/requirements?
      value: |
        > “As a [persona], I [want to], [so that].”

        1. "As a [persona]": Who are we building this for? 
        “Wants to”: Here we’re describing their intent — not the features they use. 
        “So that”: What will this enable the user to do/how will it help enable *their* needs?
            validations:
              required: true
  - type: textarea
    id: acceptance-criteria
    attributes: |
      These should stem from the user storeies and explains the things that will be `true` upon successful resolution of this issue.
      
      While not required, it may be helpful to use a `textarea` form element. 
      
      - [ ] 
  
